[bastion]
lab-bastion ansible_host=192.168.1.210 ansible_connection=local

[postgres]
lab-postgres ansible_host=10.10.0.30 ansible_user=root

[kafka]
lab-kafka ansible_host=10.10.0.31 ansible_user=root

[gitlab]
lab-gitlab ansible_host=10.10.0.12 ansible_user=root

[infra-core]
lab-infra-core ansible_host=10.10.0.32 ansible_user=root